# Generated by Django 5.1.7 on 2025-04-16 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Slam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_impression', models.TextField(blank=True, null=True)),
                ('describe_to_someone', models.TextField(blank=True, null=True)),
                ('our_campus_spot', models.TextField(blank=True, null=True)),
                ('relive_memory', models.TextField(blank=True, null=True)),
                ('relive_day', models.TextField(blank=True, null=True)),
                ('never_change', models.TextField(blank=True, null=True)),
                ('last_day_plan', models.TextField(blank=True, null=True)),
                ('best_advice', models.TimeField(blank=True, null=True)),
                ('never_forget', models.TextField(blank=True, null=True)),
                ('reunion_plan', models.TextField(blank=True, null=True)),
                ('my_life_in_ten', models.TextField(blank=True, null=True)),
                ('final_farewell', models.TextField(blank=True, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slams_from', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slams_for', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
