# Generated by Django 5.1.7 on 2025-04-17 23:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slam', '0002_alter_slam_best_advice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='slam',
            constraint=models.UniqueConstraint(fields=('to_user', 'from_user'), name='unique_slam_pair'),
        ),
    ]
