# Generated by Django 5.1.7 on 2025-04-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slam', '0003_slam_unique_slam_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='slam',
            name='status',
            field=models.BigIntegerField(choices=[(0, 'PENDING'), (1, 'SENT')], default=0),
        ),
    ]
