# Generated by Django 5.1.7 on 2025-04-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_branch_user_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='college_slug',
            field=models.CharField(default='iit roorkee', max_length=255),
            preserve_default=False,
        ),
    ]
