# Generated by Django 5.1.7 on 2025-04-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_college_college_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_slug',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]