# Generated by Django 5.1.7 on 2025-04-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic_file',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
