# Generated by Django 5.1.7 on 2025-04-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_user_profile_pic_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nostalgia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nostalgia_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='ten_on_ten',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nostalgias',
            field=models.ManyToManyField(related_name='users', to='backend.nostalgia'),
        ),
    ]
