# Generated by Django 5.1.7 on 2025-04-09 02:35

import backend.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_nostalgia_user_ten_on_ten_user_nostalgias'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'NORMAL'), (1, 'RESTAURANT')], default=0),
        ),
        migrations.CreateModel(
            name='RestaurantScenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('location_text', models.CharField(default='', max_length=255)),
                ('start_time', models.BigIntegerField(default=backend.models.get_current_unix_timestamp)),
                ('end_time', models.BigIntegerField(default=backend.models.get_current_unix_timestamp)),
                ('user_organizer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_scenes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'PENDING'), (1, 'ACCEPTED'), (2, 'REJECTED'), (3, 'CANCELLED')], default=0)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites_received', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('restaurant_scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.restaurantscenes')),
            ],
        ),
    ]
