# Generated by Django 5.1.7 on 2025-04-09 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_user_user_type_restaurantscenes_invites'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invites',
            new_name='Invite',
        ),
    ]
