# Generated by Django 5.1.7 on 2025-04-09 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_rename_invites_invite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RestaurantScenes',
            new_name='RestaurantScene',
        ),
    ]
