# Generated by Django 5.1.7 on 2025-04-09 14:05

import backend.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_rename_restaurantscenes_restaurantscene'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('notes', models.JSONField(default=list)),
                ('time', models.BigIntegerField(default=backend.models.get_current_unix_timestamp)),
                ('scene', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_items', to='backend.restaurantscene')),
            ],
        ),
    ]
