# Generated by Django 5.1.7 on 2025-04-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_notifications_scene_alter_user_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantscene',
            name='scene_image',
            field=models.TextField(default='https://github.com/shadcn.png'),
        ),
    ]
