# Generated by Django 5.1.7 on 2025-04-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_restaurantscene_scene_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantscene',
            name='scene_image',
            field=models.TextField(default='https://awsscenebucket.s3.eu-north-1.amazonaws.com/scene_default_poster.png'),
        ),
    ]
