# Generated by Django 5.1.7 on 2025-04-11 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_restaurantscene_scene_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_frequency_name', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
            options={
                'ordering': ['scene_frequency_name'],
                'indexes': [models.Index(fields=['scene_frequency_name'], name='backend_sce_scene_f_67313f_idx')],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='scene_frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.scenefrequency'),
        ),
        migrations.CreateModel(
            name='WhoIsAround',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_is_around_name', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
            options={
                'ordering': ['who_is_around_name'],
                'indexes': [models.Index(fields=['who_is_around_name'], name='backend_who_who_is__55bf08_idx')],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='who_is_around',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.whoisaround'),
        ),
    ]
