# Generated by Django 5.1.7 on 2025-04-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_scenefrequency_user_scene_frequency_whoisaround_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='scene_type',
            field=models.IntegerField(choices=[(0, 'PARTY'), (1, 'CHILL'), (2, 'TRAVEL'), (3, 'EAT')], default=0),
        ),
    ]
