# Generated by Django 5.1.7 on 2025-04-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_scene_scene_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status_text',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
