# Generated by Django 5.1.7 on 2025-04-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_usersecretdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prom_status',
            field=models.IntegerField(choices=[(0, 'LOOKING'), (1, 'COMMITED')], default=0),
        ),
    ]
