# Generated by Django 5.1.7 on 2025-04-26 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_user_prom_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='prom_status',
        ),
    ]
