# Generated by Django 5.1.7 on 2025-04-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_remove_user_prom_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender_preference',
            field=models.TextField(choices=[(0, 'MEN'), (1, 'WOMEN'), (2, 'BOTH')], default=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
