# Generated by Django 5.1.7 on 2025-04-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_user_gender_preference_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender_preference',
            field=models.IntegerField(choices=[(0, 'MEN'), (1, 'WOMEN'), (2, 'BOTH')], default=2),
        ),
    ]
