# Generated by Django 5.1.7 on 2025-04-27 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prom', '0002_userpromstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPromStatus',
        ),
    ]
